name: "Build Docs"
on: [push]
jobs:
  build-docs:
    name: Build docs site
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "8"

      - uses: actions/checkout@v4

      - name: Setup python environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: delta_docs
          environment-file: docs/apis/environment.yml

      - name: Generate API docs
        shell: bash -el {0}
        run: python3 docs/generate_docs.py

      - name: Archive docs site build
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/_site